
apiVersion: v1
kind: Service
metadata:
  name: load-balancer
  namespace: application
spec:
  type: LoadBalancer
  selector:
    app: nodejsapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
