
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejsApp
  namespace: application
spec:
  replicas: 5
  selector:
    matchLabels:
      app: nodejsapp
  template:
    metadata:
      labels:
        app: nodejsapp
    spec:
      containers:
        - name: nodejsapp
          image: docker.io/zeyad13/appimage22
          ports:
            - name: httpport
              containerPort: 3000
      
